### PR TITLE
ISO/FDIS 19131 requirements

### PR DESCRIPTION
**Pull request by ronaldtse**
From @magnusKarge , originally in #5 .

> Implemented changes according to FDIS 19131. I also added actual content to the index files (was TBD before).

### CODE REVIEW

**Comment by magnusKarge** [comment]
Ronald,

The project team have now come to the FDIS stage. According to ISO CS they want to finalize the document today. We can make the content of that request publicly available.

Anything left that I need to do? You mentioned typos (where are those, if not fixed yet?).

**Comment by ronaldtse** [comment]
@magnusKarge that's great to know! I was also alerted by @MatsAhlin about this but wasn't sure when this should go live.

There are typos like this:
https://github.com/ISO-TC211/standards.isotc211.org/blame/feature/19131-fdis/standards/19131/-/2/conf/xml/xmlEncoding/index.adoc

Screen Shot 2020-05-04 at 7 21 09 PM

But I'll do a quality check and handle them from here.

**Review by magnusKarge — APPROVED** [review]

**Comment by ronaldtse** [comment]
@magnusKarge it's merged -- can you notify ISO/CS? Thanks!

**Comment by magnusKarge** [comment]
Thanks, I forwarded this information to @MatsAhlin he is the project team's contact point for ISO/CS.

Thanks again.

**Comment by MatsAhlin** [comment]
ISO/CS was happy with the knowledge of we getting the job done. The FDIS ballot will start on the 18 of may and have been posted in the ballot portal.
Thanks everyone for the god work.

**Comment by ronaldtse** [comment]
Thanks @MatsAhlin @magnusKarge !

**Pull request merged**
