### PR TITLE
FDIS changes

### PR DESCRIPTION
**Pull request by magnusKarge**
Implemented changes according to FDIS 19131. I also added actual content to the index files (was TBD before).

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @magnusKarge ! Are you planning to get this merged on publication of 19131?

**Comment by magnusKarge** [comment]
I think we can wait with merging until FDIS 19131 is out for ballot. On the other hand, we may at any time update what already is online for 19131. Probably @jetgeo has some guidance as well?

**Comment by ronaldtse** [comment]
@magnusKarge there are some typos in the PR. If you don't mind how about we merge your commits into to a separate branch of this repo and we can make the necessary fixes here? I believe you have access to this repo, right?

**Comment by magnusKarge** [comment]
Good idea, unfortunately I don't have access to this repository. At least I was not able to create a branche here, when I started to work on the URIs for 19131.

**Comment by ronaldtse** [comment]
@magnusKarge just added you for convenience. Merging this into the new `feature/19131-fdis` branch!

**Comment by magnusKarge** [comment]
Thank you!

**Pull request merged**
